services:
  db:
    image: mariadb
    restart: always
    ports: 
      - "3306:3306"
    expose: 
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
